### ISSUE TITLE
issue test

### ISSUE THREAD

**Issue by adesight** [adesight/git-study#6]
t2?

**Comment by adesight** [comment]
ah What's this...
🔢

**Comment by isLishude** [comment]
I have a solve... 

> ah What's this...

**Comment by adesight** [comment]
@isLishude what ..

**Comment by isLishude** [comment]
https://github.com/adesight/git-study/issues/6#issuecomment-268991207
>fixed

**Comment by adesight** [comment]
#10

**Comment by isLishude** [comment]
have a trobble
